# FORMA COMUN DE DECLARAR LOS ARREGLOS, LES ASIGNO UN TAMAÑO Y LISTO
ar1 = [0] * 4  
ar2 = [''] * 4  
ar3 = [0.0] * 4  

# LES ASIGNO UN TAMAÑO Y VALORES YA INICIALIZADOS O LLENADO
ar4 = [1, 2, 3, 4]
ar5 = ['a', 'b', 'c', 'd']
ar6 = [2.4, 3.0, 23.0, 6.0]

# ESTA FORMA NO LA ENTIENDO MUY BIEN, ARREGLO DINAMICO. 
arr = [0 for _ in range(4)]  

print("PRACTICA NO.1 DECLARACION E INICIALIZACION DE ARREGLOS EN PYTHON")
